excluded:
  - Pods

trailing_comma:
  mandatory_comma: true

identifier_name:
  min_length: 2

function_parameter_count:
  warning: 8
  error: 8 

type_body_length: 
  warning: 300
  error: 300 

line_length: 
  warning: 200
  error: 200 
