platform :ios, '15.0'

target 'RxCocoaMVVMExampleLoginForm' do
  use_frameworks!
  inhibit_all_warnings!

  pod 'RxSwift'
  pod 'RxSwiftExt'
  pod 'RxCocoa'
  pod 'JGProgressHUD'
  pod 'SwiftFormat/CLI'
  pod 'SwiftGen'
  pod 'SwiftLint'
  pod 'Swinject'
end
